gestion/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from gestion import views, forms

app_name = "gestion"

urlpatterns = [
    url(r'^$', views.Dashboard.as_view(), name='dashboard'),
    url(r'^profesores/$', views.ListarProfesores.as_view(), name='listar-profesores'),
    url(r'^profesores/agregar/$', views.AgregarProfesor.as_view(), name='agregar-profesor'),
    url(r'^profesores/editar/(?P<pk>[-\w]+)/$', views.EditarProfesor.as_view() , name='editar-profesor'),
    url(r'^profesores/eliminar/(?P<pk>[-\w]+)/$', views.EliminarProfesor.as_view() , name='eliminar-profesor'),
    url(r'^profesores/(?P<pk>[-\w]+)/$', views.VerProfesor.as_view(), name='ver-profesor'),
    url(r'^asignaturas/$', views.ListarAsignaturas.as_view(), name='listar-asignaturas'),
    url(r'^asignaturas/agregar/$', views.AgregarAsignatura.as_view(), name='agregar-asignatura'),
    url(r'^asignaturas/editar/(?P<pk>[-\w]+)/$', views.EditarAsignatura.as_view() , name='editar-asignatura'),
    url(r'^asignaturas/eliminar/(?P<pk>[-\w]+)/$', views.EliminarAsignatura.as_view() , name='eliminar-asignatura'),
    url(r'^asignaturas/(?P<pk>[-\w]+)/$', views.VerAsignatura.as_view(), name='ver-asignatura'),
    url(r'^ofertas/$', views.ListarOfertas.as_view(), name='listar-ofertas'),
    url(r'^ofertas/agregar/$', views.AgregarOferta.as_view([
        forms.AgregarOfertaTrimestralPaso1,
        forms.AgregarOfertaTrimestralPaso2
    ]), name='agregar-oferta'),
    url(r'^ofertas/agregar/(?P<pk>[-\w]+)/$', views.AgregarOferta.as_view([
        forms.AgregarOfertaTrimestralPaso1,
        forms.AgregarOfertaTrimestralPaso2
    ]), name='agregar-oferta'),
    url(r'^ofertas/eliminar/(?P<pk>[-\w]+)/$', views.EliminarOferta.as_view(), name='eliminar-oferta'),
    url(r'^ofertas/modificar/(?P<pk>[-\w]+)/$', views.ModificarOferta.as_view(), name='modificar-oferta'),
    url(r'^ofertas/buscar/$', views.buscar_oferta, name='buscar-ofertas'),
    url(r'^ofertas/buscar/(?P<periodo>[-\w]+)/$', views.buscar_oferta, name='buscar-ofertas'),
    url(r'^ofertas/buscar/(?P<periodo>[-\w]+)/(?P<ano>[-\w]+)/$', views.buscar_oferta, name='buscar-ofertas'),
    url(r'^ofertas/(?P<pk>[-\w]+)/$', views.VerOferta.as_view(), name='ver-oferta'),
    url(r'^ofertas-asignacion/$', views.ListarOfertasIncluyentes.as_view(), name='listar-ofertas-asignacion'),
    url(r'^ofertas-asignacion/actualizar/(?P<pk_oferta>[-\w]+)/$', views.actualizar_preferencias, name='actualizar-preferencias'),
    url(r'^ofertas-asignacion/(?P<pk>[-\w]+)/$', views.VerOfertaIncluyente.as_view(), name='ver-oferta-asignacion'),
    url(r'^ofertas-coordinacion/$', views.ListarOfertasCoordinacion.as_view(), name='listar-ofertas-coordinacion'),
    url(r'^ofertas-coordinacion/(?P<pk>[-\w]+)/$', views.VerOfertaCoordinacion.as_view(), name='ver-oferta-coordinacion'),
    url(r'^cambiar-contrasena/', views.cambiar_contrasena, name='cambiar-contrasena'),
]

sip/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^login/$', auth_views.login, {'template_name': 'sesiones/login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^admin/', admin.site.urls),
    url(r'^chat/', include('conversate.urls', namespace='conversate')),
    url(r'', include('gestion.urls')),
]

templates/ofertas/agregar.html
<div class="modal-header">
    <h5 class="modal-title" id="largeModalLabel">Agregar Oferta Trimestral (paso {{ wizard.steps.step1 }} de {{ wizard.steps.count }})</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<div class="modal-body" id="prueba">
    <form method="POST" class="post-form form-horizontal" action="{% url 'gestion:agregar-oferta' %}" id="f{{ wizard.steps.step1 }}">
        {% csrf_token %}
        {{ wizard.management_form }}
        {% if wizard.form.forms %}
            {{ wizard.form.management_form }}
            {% for form in wizard.form.forms %}
                {% for field in form %}
                <div class="row form-group">
                    <div class="col-md-3">
                        <label class="form-control-label">{{ field.label_tag }}</label>
                    </div>
                    <div class="col-md-9">
                        {{ field }}
                    </div>
                </div>
                {% endfor %}
            {% endfor %}
        {% else %}
            {% for field in wizard.form  %}
                {% if wizard.steps.step1 == 1 or field.html_name|slice:"13:" in ids_asignaturas %}
                <div class="row form-group">
                    <div class="col-md-3">
                        <label class="form-control-label">
                            {% if wizard.steps.step1 == 1 %}
                                {{ field.label_tag }}
                            {% else %}
                                {{ nombres_asignaturas|dict_key:field.html_name }}
                            {% endif %}
                        </label>
                    </div>
                    <div class="col-md-9">
                        {{ field }}
                    </div>
                </div>
                {% endif %}
            {% endfor %}
        {% endif %}
    </form>
</div>
<div class="modal-footer">
    {% if wizard.steps.prev %}
        <button style="display:none; visibility: hidden;" name="wizard_goto_step" form="f{{ wizard.steps.step1 }}" class="btn btn-secondary" type="submit" value="{{ wizard.steps.prev }}">Regresar</button>
    {% endif %}
    {% if wizard.steps.step1 != 1 %}
        <button type="submit" class="btn btn-primary" form="f{{ wizard.steps.step1 }}" value="Submit">Agregar</button>
    {% else %}
        <button type="submit" class="btn btn-primary" form="f{{ wizard.steps.step1 }}" value="Submit">Continuar</button>
    {% endif %}
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
</div>

{% if wizard.steps.step1 == 1 %}
<script>
    $('#modalCRUD').on('submit', '#f1' , function(e){
        e.preventDefault();
        var fd = new FormData($('#f1').get(0));
        $.ajax({
            url: "{% url 'gestion:agregar-oferta' %}",
            data: fd,
            type: "POST",
            success: function(data){
                    $('.modal-content').html(data);
                },
            processData: false,
            contentType: false
        });
    });

    $('#agregar-asignatura').click(function() {
        $.ajax({
            url: "{% url 'gestion:agregar-asignatura' %}",
            type: "GET",
            success: function(data){
                    $('.modal-content').html(data);
                },
            processData: false,
            contentType: false
        });
    });
</script>
{% endif %}

templates/ofertas/buscar.html
{% extends 'base.html' %}

{% block title %}Buscar ofertas finales{% endblock %}

{% block content %}
<div class="col-md-12">

  {% if messages %}
    {% for message in messages %}
      <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %} alert-dismissible fade show">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Cerrar">
            <span aria-hidden="true">×</span>
        </button>
      </div>
    {% endfor %}
  {% endif %}

    <div class="card">
        <div class="card-header">
            <h4>Buscar Ofertas Finales</h4>
        </div>
        <div class="card-body">
            <div class="row">
                <form class="form form-horizontal" style="width: 100%;" method="post" action="{% url 'gestion:buscar-ofertas' %}">
                    {% csrf_token %}
                    <div class="col-md-3">
                        <div class="form-group row">
                            <label class="form-group col-sm-4 col-form-label text-right"><b>Período</b></label>
                            <select class="form-control col-sm-8" name="periodo" id="periodo">
                                <option value="-">Seleccione una opción</option>
                                <option value="EM">Enero-Marzo</option>
                                <option value="AJ">Abril-Julio</option>
                                <option value="JA">Julio-Agosto</option>
                                <option value="SD">Septiembre-Diciembre</option>
                            </select>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group row">
                            <label class="form-group col-sm-4 col-form-label text-right"><b>Año</b></label>
                            <input class="form-control col-sm-8" type="number" name="ano" id="ano" min="1967" />
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group row">
                            <label class="form-group col-sm-4 col-form-label text-right"><b>Solo ofertas de mi Dpto</b></label>
                            <select class="form-control col-sm-8" name="filtrar_dpto" id="filtrar_dpto">
                                <option value="No">No</option>
                                <option value="Sí">Sí</option>
                            </select>
                        </div>
                    </div>
                    <div class="col-md-2">
                        <button type="submit" class="btn btn-primary">Buscar</button>
                    </div>

                </form>
            </div>

            <div id="resultados">
                <div class="row">
                    {% for oferta in ofertas %}
                    <div class="col-md-4">
                        <div class="card">
                            <div class="card-body">
                                <h5 class="card-title">{{ oferta.nombre_completo }}</h5>
                                <p class="card-text">{{ oferta.departamento }}</p>
                                {% if oferta.departamento.jefe == request.user.profesor %}
                                    <a href="#" class="card-link trigger" data-toggle="modal" data-target="#modalCRUD" data-url="{% url 'gestion:agregar-oferta' oferta.pk %}">Usar de base</a>
                                {% endif %}
                                <a href="#" class="card-link trigger" data-toggle="modal" data-target="#modalCRUD" data-url="{% url 'gestion:ver-oferta' oferta.pk %}">Ver más detalles</a>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade show" id="modalCRUD" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
    </div>
  </div>
</div>
{% endblock %}

{% block js %}
<script type="text/javascript">
  $('.trigger').on('click', function(e) {
    const $this = $(this)
    // Seleccionamos tamaño del modal de acuerdo al botón
    // que escogimos
    if ($this.hasClass('fa-eye')) {
      $('.modal-dialog').removeClass( "modal-md" );
      $('.modal-dialog').addClass( "modal-lg" );
    } else {
      $('.modal-dialog').removeClass( "modal-lg" );
      $('.modal-dialog').addClass( "modal-md" );
    }
    // Cargamos la información para el modal de acuerdo al botón al que
    // hicimos click
    $.ajax({
      url: $this.data('url'),
      method: 'GET',
      success: function(data) {
          $('#modalCRUD .modal-content').html(data);
      }
    });
  });
</script>
{% endblock %}

{% block css %}
<style type="text/css">
/* Aquí va codigo css personalziado dentro de etiquetas style */
</style>
{% endblock %}

templates/ofertas/eliminar.html
<div class="modal-header">
    <h5 class="modal-title" id="largeModalLabel">Eliminar oferta trimestral</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<div class="modal-body">
    <p>
        ¿Esta seguro de querer eliminar la oferta trimestral de {{ ofertatrimestral.nombre_completo }} ofertada por el {{ ofertatrimestral.departamento }}?
        Por favor, confirme la acción con los botones inferiores.
        </p>
        <form method="post" action="{% url 'gestion:eliminar-oferta' ofertatrimestral.pk %}" id="f1">
            {% csrf_token %}
        </form>
</div>
<div class="modal-footer">
    <button type="submit" class="btn btn-danger" form="f1" value="Submit" form="f1">Confirmar</button>
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
</div>

templates/ofertas/listar.html
{% extends 'base.html' %}

{% block title %}Gestionar ofertas{% endblock %}

{% block content %}
<div class="col-md-12">

  {% if messages %}
    {% for message in messages %}
      <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %} alert-dismissible fade show">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Cerrar">
            <span aria-hidden="true">×</span>
        </button>
      </div>
    {% endfor %}
  {% endif %}

    <div class="card">
        <div class="card-header">
            <h4>Ofertas Finales</h4>
        </div>
        <div class="card-body">

            <table id="bootstrap-data-table" class="table table-striped table-bordered">
              <thead>
                <tr>
                  <th>Código</th>
                  <th>Nombre</th>
                  <th>Departamento</th>
                  <th>Estado</th>
                  <th>Acciones</th>
                </tr>
              </thead>
              <tbody>
                {% for oferta in ofertas %}
                  {% if oferta.estado == 'final' %}
                  <tr>
                    <td>{{ oferta.trimestre }}</td>
                    <td>{{ oferta.nombre_completo }}</td>
                    <td>{{ oferta.departamento }}</td>
                    <td>
                        <span class="badge {% if oferta.estado == 'final' %} badge-success {% else %} badge-info {% endif %}">
                          {{ oferta.estado }}
                        </span>
                    </td>
                    <td class="acciones">
                      <i class="fa fa-eye trigger" class="boton-ver" data-toggle="modal" data-target="#modalCRUD" data-url="{% url 'gestion:ver-oferta' oferta.pk %}" aria-hidden="true"></i>
                      &nbsp;
                      <i class="fa fa-pencil trigger" class="boton-editar" data-toggle="modal" data-target="#modalCRUD" data-url="{% url 'gestion:modificar-oferta' oferta.pk %}" aria-hidden="true"></i>
                      &nbsp;
                      <i class="fa fa-trash-o trigger" class="boton-eliminar" data-toggle="modal" data-target="#modalCRUD" data-url="{% url 'gestion:eliminar-oferta' oferta.pk %}" aria-hidden="true"></i>
                    </td>
                  </tr>
                  {% endif %}
              	{% endfor %}
              </tbody>
            </table>
        </div>
    </div>

    <div class="card">
        <div class="card-header">
            <button type="button" data-toggle="modal" data-target="#modalCRUD" class="btn btn-primary float-right trigger" form="f1" data-url="{% url 'gestion:agregar-oferta' %}">Agregar</button>
            <h4>Ofertas Preliminares</h4>
        </div>
        <div class="card-body">

            <table id="bootstrap-data-table2" class="table table-striped table-bordered">
              <thead>
                <tr>
                  <th>Código</th>
                  <th>Nombre</th>
                  <th>Departamento</th>
                  <th>Estado</th>
                  <th>Acciones</th>
                </tr>
              </thead>
              <tbody>
                {% for oferta in ofertas %}
                  {% if oferta.estado == 'preliminar' %}
                  <tr>
                    <td>{{ oferta.trimestre }}</td>
                    <td>{{ oferta.nombre_completo }}</td>
                    <td>{{ oferta.departamento }}</td>
                    <td>
                        <span class="badge {% if oferta.estado == 'final' %} badge-success {% else %} badge-info {% endif %}">
                          {{ oferta.estado }}
                        </span>
                    </td>
                    <td class="acciones">
                      <i class="fa fa-eye trigger" class="boton-ver" data-toggle="modal" data-target="#modalCRUD" data-url="{% url 'gestion:ver-oferta' oferta.pk %}" aria-hidden="true"></i>
                      &nbsp;
                      <i class="fa fa-trash-o trigger" class="boton-eliminar" data-toggle="modal" data-target="#modalCRUD" data-url="{% url 'gestion:eliminar-oferta' oferta.pk %}" aria-hidden="true"></i>
                    </td>
                  </tr>
                  {% endif %}
                {% endfor %}
              </tbody>
            </table>
        </div>
    </div>
</div>

<div class="modal fade show" id="modalCRUD" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
    </div>
  </div>
</div>
{% endblock %}

{% block js %}
<script type="text/javascript">
  window.alert = function() {};
  $('.trigger').on('click', function(e) {
    const $this = $(this)
    // Seleccionamos tamaño del modal de acuerdo al botón
    // que escogimos
    if ($this.hasClass('fa-eye') || $this.hasClass('fa-pencil')) {
      $('.modal-dialog').removeClass( "modal-md" );
      $('.modal-dialog').addClass( "modal-lg" );
    } else {
      $('.modal-dialog').removeClass( "modal-lg" );
      $('.modal-dialog').addClass( "modal-md" );
    }
    // Cargamos la información para el modal de acuerdo al botón al que
    // hicimos click
    $.ajax({
      url: $this.data('url'),
      method: 'GET',
      success: function(data) {
        $('#modalCRUD .modal-content').html(data);
        $('input').addClass( "form-control" );
       $('select').not('select[name=bootstrap-data-table_length]').not('select[name=bootstrap-data-table2_length]').addClass( "form-control chosen" );
       $('select').not('select[name=bootstrap-data-table_length]').not('select[name=bootstrap-data-table2_length]').attr('data-placeholder', 'Selecciona una o varias opciones...');
        $(".chosen").chosen({ width: '100%', no_results_text: "No hay resultados para: "});
        $('.tablafinal').DataTable({
          "language": {
              "url": "https://cdn.datatables.net/plug-ins/1.10.19/i18n/Spanish.json"
          }
        });
      }
    })
  })
</script>
{% endblock %}

{% block css %}
<style type="text/css">
/* Aquí va codigo css personalziado dentro de etiquetas style */
</style>
{% endblock %}

templates/ofertas/modificar.html
{% load dict_key %}
<div class="modal-header">
    <h5 class="modal-title" id="largeModalLabel">Detalles de la oferta trimestral</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<div class="modal-body">
    <h1 class="text-center"> {{ oferta.nombre_completo }} </h1>
    <hr />
    <div class="row">
        <div class="col-md-3 float-right">
            <b>Código</b>
        </div>
        <div class="col-md-9">
            {{ oferta.trimestre }}
        </div>
        <div class="col-md-3 float-right">
            <b>Departamento</b>
        </div>
        <div class="col-md-9">
            {{ oferta.departamento }}
        </div>
        <div class="col-md-3 float-right">
            <b>Estatus</b>
        </div>
        <div class="col-md-9">
                <span class="badge {% if oferta.estado == 'final' %} badge-success {% else %} badge-info {% endif %}">
                    {{ oferta.estado }}
                </span>
        </div>
    </div>

    <hr/>
    {% if oferta.estado == "final"%}
        <form method="post" action="{% url 'gestion:modificar-oferta' oferta.pk %}" id="f1">
            {% csrf_token %}
            <div class="card text-center">
                <div class="card-header">
                    <b>Modificar asignaciones existentes</b>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <input type="hidden" name="oferta_id" value="{{ oferta.pk }}" />
                        <table class="table">
                            <thead>
                                <th>Asignatura</th>
                                <th>Profesor</th>
                                <th>Preferencia</th>
                                <th>Marcar como Final</th>
                            </thead>
                            <tbody>
                                {% for asignacion in asignaciones %}
                                    <tr>
                                        <td>{{ asignacion.asignatura }}</td>
                                        <td>{{ asignacion.profesor }}</td>
                                        <td>
                                            {% if asignacion.es_preferida %}
                                            <span class="badge badge-success">
                                                PREFERIDA
                                            </span>
                                            {% endif %}
                                        </td>
                                        <td><input type="checkbox" class="form-control" name="botonElegir_{{ asignacion.id }}" {% if asignacion.es_final %} checked {% endif %} /></td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                        <br/>
                        Para eliminar una asignación de la oferta, desmárquela como final.
                    </div>
                </div>
            </div>

            {% if hay_asignaciones_nuevas or hay_asignaturas_no_ofertadas %}
                <div class="card text-center">
                    <div class="card-header">
                        Opciones
                    </div>
                    <div class="card-body">
                        {% if hay_asignaciones_nuevas %}
                            <button class="btn btn-success mr-10" type="button" data-toggle="collapse" data-target="#asignaciones_nuevas" aria-expanded="false" aria-controls="asignaciones_nuevas">
                                Asignar nuevos profesores
                            </button>
                        {% endif %}

                        {% if hay_asignaturas_no_ofertadas %}
                            <button class="btn btn-success" type="button" data-toggle="collapse" data-target="#asignaturas_no_ofertadas" aria-expanded="false" aria-controls="asignaturas_no_ofertadas">
                                Agregar asignaturas
                            </button>
                        {% endif %}
                    </div>
                </div>
            {% endif %}

            {% if hay_asignaciones_nuevas %}
                <div class="collapse" id="asignaciones_nuevas">
                    <div class="card text-center">
                        <div class="card-header">
                            <b>Asignar nuevos profesores</b>
                        </div>
                        <div class="card-body">
                            <div class="table-responsive">
                                <input type="hidden" name="oferta_id" value="{{ oferta.pk }}" />
                                <table class="table tablafinal">
                                    <thead>
                                        <th>Asignatura</th>
                                        <th>Profesor</th>
                                        <th>Agregar</th>
                                    </thead>
                                    <tbody>
                                        {% for asignatura, profesores in asignaciones_nuevas.items %}
                                            {% for profesor in profesores %}
                                                <tr>
                                                    <td>{{ asignatura }}</td>
                                                    <td>{{ profesor }}</td>
                                                    <td><input type="checkbox" class="form-control" name="botonAgregar_{{ asignatura.id }}_{{ profesor.id }}" /></td>
                                                </tr>
                                            {% endfor%}
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            {% endif %}

            {% if hay_asignaturas_no_ofertadas %}
                <div class="collapse" id="asignaturas_no_ofertadas">
                    <div class="card text-center">
                        <div class="card-header">
                            <b>Agregar asignaturas nuevas</b>
                        </div>
                        <div class="card-body">
                            <div class="table-responsive">
                                <input type="hidden" name="oferta_id" value="{{ oferta.pk }}" />
                                <table class="table tablafinal">
                                    <thead>
                                        <th>Asignatura</th>
                                        <th>¿Agregar?</th>
                                        <th>Profesores</th>
                                    </thead>
                                    <tbody>
                                        {% for asignatura, profesores in asignaturas_no_ofertadas.items %}
                                        <tr>
                                            <td>{{ asignatura }}</td>
                                            <td><input type="checkbox" class="form-control" name="botonNueva_{{ asignatura.id }}" /></td>
                                            <td>
                                                <select class="form-control" id="opciones_{{ asignatura.id }}" name="opciones_{{ asignatura.id }}" multiple="multiple">
                                                    {% for profesor in profesores %}
                                                        <option value="{{ profesor.id }}">{{ profesor }}</option>
                                                    {% endfor %}
                                                </select>
                                            </td>
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            {% endif %}
        </form>
    {% endif %}
 </div>

<div class="modal-footer">
{% if oferta.estado == "final"%}
    <button type="submit" form="f1" value="Submit" class="btn btn-primary">Modificar oferta</button>
{% endif %}
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
</div>