gestion/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from gestion import views, forms

app_name = "gestion"

urlpatterns = [
    url(r'^$', views.Dashboard.as_view(), name='dashboard'),
    url(r'^profesores/$', views.ListarProfesores.as_view(), name='listar-profesores'),
    url(r'^profesores/agregar/$', views.AgregarProfesor.as_view(), name='agregar-profesor'),
    url(r'^profesores/editar/(?P<pk>[-\w]+)/$', views.EditarProfesor.as_view() , name='editar-profesor'),
    url(r'^profesores/eliminar/(?P<pk>[-\w]+)/$', views.EliminarProfesor.as_view() , name='eliminar-profesor'),
    url(r'^profesores/(?P<pk>[-\w]+)/$', views.VerProfesor.as_view(), name='ver-profesor'),
    url(r'^asignaturas/$', views.ListarAsignaturas.as_view(), name='listar-asignaturas'),
    url(r'^asignaturas/agregar/$', views.AgregarAsignatura.as_view(), name='agregar-asignatura'),
    url(r'^asignaturas/editar/(?P<pk>[-\w]+)/$', views.EditarAsignatura.as_view() , name='editar-asignatura'),
    url(r'^asignaturas/eliminar/(?P<pk>[-\w]+)/$', views.EliminarAsignatura.as_view() , name='eliminar-asignatura'),
    url(r'^asignaturas/(?P<pk>[-\w]+)/$', views.VerAsignatura.as_view(), name='ver-asignatura'),
    url(r'^ofertas/$', views.ListarOfertas.as_view(), name='listar-ofertas'),
    url(r'^ofertas/agregar/$', views.AgregarOferta.as_view([
        forms.AgregarOfertaTrimestralPaso1,
        forms.AgregarOfertaTrimestralPaso2
    ]), name='agregar-oferta'),
    url(r'^ofertas/agregar/(?P<pk>[-\w]+)/$', views.AgregarOferta.as_view([
        forms.AgregarOfertaTrimestralPaso1,
        forms.AgregarOfertaTrimestralPaso2
    ]), name='agregar-oferta'),
    url(r'^ofertas/eliminar/(?P<pk>[-\w]+)/$', views.EliminarOferta.as_view(), name='eliminar-oferta'),
    url(r'^ofertas/modificar/(?P<pk>[-\w]+)/$', views.ModificarOferta.as_view(), name='modificar-oferta'),
    url(r'^ofertas/buscar/$', views.buscar_oferta, name='buscar-ofertas'),
    url(r'^ofertas/buscar/(?P<periodo>[-\w]+)/$', views.buscar_oferta, name='buscar-ofertas'),
    url(r'^ofertas/buscar/(?P<periodo>[-\w]+)/(?P<ano>[-\w]+)/$', views.buscar_oferta, name='buscar-ofertas'),
    url(r'^ofertas/(?P<pk>[-\w]+)/$', views.VerOferta.as_view(), name='ver-oferta'),
    url(r'^ofertas-asignacion/$', views.ListarOfertasIncluyentes.as_view(), name='listar-ofertas-asignacion'),
    url(r'^ofertas-asignacion/actualizar/(?P<pk_oferta>[-\w]+)/$', views.actualizar_preferencias, name='actualizar-preferencias'),
    url(r'^ofertas-asignacion/(?P<pk>[-\w]+)/$', views.VerOfertaIncluyente.as_view(), name='ver-oferta-asignacion'),
    url(r'^ofertas-coordinacion/$', views.ListarOfertasCoordinacion.as_view(), name='listar-ofertas-coordinacion'),
    url(r'^ofertas-coordinacion/(?P<pk>[-\w]+)/$', views.VerOfertaCoordinacion.as_view(), name='ver-oferta-coordinacion'),
    url(r'^cambiar-contrasena/', views.cambiar_contrasena, name='cambiar-contrasena'),
]

sip/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^login/$', auth_views.login, {'template_name': 'sesiones/login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^admin/', admin.site.urls),
    url(r'^chat/', include('conversate.urls', namespace='conversate')),
    url(r'', include('gestion.urls')),
]

templates/asignaturas/agregar.html
<div class="modal-header">
    <h5 class="modal-title" id="largeModalLabel">Agregar asignatura</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<div class="modal-body">
    <form method="POST" class="post-form form-horizontal" action="{% url 'gestion:agregar-asignatura' %}" id="f1">
        {% csrf_token %}
        {% for field in form %}
        <div class="row form-group">
            <div class="col-md-3">
                <label class=" form-control-label">{{ field.label_tag }}</label>
            </div>
            <div class="col-md-9">
                {{ field }}
            </div>
      </div>
        {% endfor %}
    </form>
</div>
<div class="modal-footer">
    <button type="submit" class="btn btn-primary" form="f1" value="Submit">Agregar</button>
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
</div>

templates/asignaturas/editar.html
<div class="modal-header">
    <h5 class="modal-title" id="largeModalLabel">Editar {{ asignatura.nombre }} {{ asignatura.codigo_interno}}</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<div class="modal-body">
    <p>         
        <form method="POST" action="{% url 'gestion:editar-asignatura' asignatura.pk %}" id="f1" class="post-form">
            {% csrf_token %}
            {% for field in form %}
            <div class="row form-group">
                <div class="col-md-3">
                    <label class=" form-control-label">{{ field.label_tag }}</label>
                </div>
                <div class="col-md-9">
                    {{ field }}
                </div>
            </div>
            {% endfor %}
        </form>
    </p>
</div>
<div class="modal-footer">
    <button type="submit" class="btn btn-primary" form="f1">Modificar</button>
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
</div>

templates/asignaturas/eliminar.html
<div class="modal-header">
    <h5 class="modal-title" id="largeModalLabel">Eliminar asignatura</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<div class="modal-body">
    <p>
        ¿Esta seguro de querer eliminar la asignatura {{ asignatura.nombre }} ({{ asignatura.codigo_completo }})? 
        Por favor, confirme la acción con los botones inferiores.
        </p>
        <form method="post" action="{% url 'gestion:eliminar-asignatura' asignatura.pk %}" id="f1">
            {% csrf_token %}
        </form>
</div>
<div class="modal-footer">
    <button type="submit" class="btn btn-danger" form="f1" value="Submit" form="f1">Confirmar</button>
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
</div>

templates/asignaturas/listar.html
{% extends 'base.html' %}

{% block title %}Gestión de asignaturas{% endblock %}

{% block content %}
<div class="col-md-12">

  {% if messages %}
    {% for message in messages %}
      <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %} alert-dismissible fade show">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Cerrar">
            <span aria-hidden="true">×</span>
        </button>
      </div>
    {% endfor %}
  {% endif %}

    <div class="card">
        <div class="card-header">
            <button type="button" data-toggle="modal" data-target="#modalCRUD" class="btn btn-primary float-right trigger" form="f1" data-url="{% url 'gestion:agregar-asignatura' %}">Agregar</button>
            <h4>Asignaturas</h4>
        </div>
        <div class="card-body">

            <table id="bootstrap-data-table" class="table table-striped table-bordered">
              <thead>
                <tr>
                  <th>Código</th>
                  <th>Nombre</th>
                  <th>Departamento</th>
                  <th>Acciones</th>
                </tr>
              </thead>
              <tbody>
              	{% for asignatura in asignaturas %}
              	<tr>
                  <td>{{ asignatura.codigo_completo}}</td>
              		<td>{{ asignatura.nombre }}</td>
              		<td>{{ asignatura.departamento }}</td>
              		<td class="acciones">
                    <i class="fa fa-eye trigger" class="boton-ver" data-toggle="modal" data-target="#modalCRUD" data-url="{% url 'gestion:ver-asignatura' asignatura.pk %}" aria-hidden="true"></i>
                    &nbsp;
                    <i class="fa fa-pencil trigger" class="boton-editar" data-toggle="modal" data-target="#modalCRUD" data-url="{% url 'gestion:editar-asignatura' asignatura.pk %}" aria-hidden="true"></i>
                    &nbsp;
                    <i class="fa fa-trash-o trigger" class="boton-eliminar" data-toggle="modal" data-target="#modalCRUD" data-url="{% url 'gestion:eliminar-asignatura' asignatura.pk %}" aria-hidden="true"></i>  
                  </td>
              	</tr>
              	{% endfor %}
              </tbody>
            </table>
        </div>
    </div>
</div>

<div class="modal fade show" id="modalCRUD" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
    </div>
  </div>
</div>
{% endblock %}

{% block js %}
<script type="text/javascript">
  $('.trigger').on('click', function(e) {
    const $this = $(this)

    // Seleccionamos tamaño del modal de acuerdo al botón
    // que escogimos
    if ($this.hasClass('fa-eye')) {
      $('.modal-dialog').removeClass( "modal-md" );
      $('.modal-dialog').addClass( "modal-lg" );
    } else {
      $('.modal-dialog').removeClass( "modal-lg" );
      $('.modal-dialog').addClass( "modal-md" );
    }

    // Cargamos la información para el modal de acuerdo al botón al que
    // hicimos click
    $.ajax({
      url: $this.data('url'),
      method: 'GET',
      success: function(data) {
          $('#modalCRUD .modal-content').html(data);
          $('input').addClass( "form-control" );
         $('select').not('select[name=bootstrap-data-table_length]').not('select[name=bootstrap-data-table2_length]').addClass( "form-control chosen" );
         $('select').not('select[name=bootstrap-data-table_length]').not('select[name=bootstrap-data-table2_length]').attr('data-placeholder', 'Selecciona una o varias opciones...');
          $(".chosen").chosen({ width: '100%', no_results_text: "No hay resultados para: "});

          var regExpMask = new IMask(
          document.getElementById('cedula'), // aquí el valor debería ser 'id_cedula'
          {
            mask: /$^/ // aquí debería ir un regex
          });
      }
    })
  })

</script>
{% endblock %}

{% block css %}
<style type="text/css">
/* Aquí va codigo css personalziado dentro de etiquetas style */
</style>
{% endblock %}

templates/asignaturas/ver.html
{% load dict_key %}
<div class="modal-header">
    <h5 class="modal-title" id="largeModalLabel">Detalles de la asignatura</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<div class="modal-body">
    <h1 class="text-center"> {{ asignatura.nombre }} </h1>
    <hr />
    <div class="row">
        <div class="col-md-3 float-right">
            <b>Código</b>
        </div>
        <div class="col-md-9">
            {{ asignatura.codigo_completo }}
        </div>
        <div class="col-md-3 float-right">
            <b>Departamento</b>
        </div>
        <div class="col-md-9">
            {{ asignatura.departamento }}
        </div>
		<div class="col-md-3 float-right">
		    <b>Unidades de Crédito (U.C.)</b>
		</div>
		<div class="col-md-9">
		   {{ asignatura.unidad_creditos }}
    	</div>
    	<div class="col-md-3 float-right">
		    <b>Horas de teoría</b>
		</div>
		<div class="col-md-9">
		   {{ asignatura.horas_teoria }}
    	</div>
    	<div class="col-md-3 float-right">
    		<b>Horas de laboratorio</b>
    	</div>
    	<div class="col-md-9">
    		{{ asignatura.horas_laboratorio }}
    	</div>
    	<div class="col-md-3 float-right">
    	 	<b>Horas de práctica</b>
    	</div>
    	<div class="col-md-9">
    	    {{ asignatura.horas_practica }}
        </div>
    </div>
    <hr/>

    <div class="card text-center">
        <div class="card-header">
            <b>Requisitos (prelada por)</b>
        </div>
        <ul class="list-group list-group-flush">
            {% for asignatura in asignatura.requisitos.all %}
                <li class="list-group-item">{{ asignatura }}</li>
            {% empty %}
            <li class="list-group-item">Ninguna asignatura por el momento...</li>
            {% endfor %}
        </ul>
    </div>

    <div class="card text-center">
        <div class="card-header">
            <b>Profesores disponibles para dictarla</b>
        </div>
        <ul class="list-group list-group-flush">
            {% for profesor in asignatura.profesores %}
                <li class="list-group-item">{{ profesor.nombre }} {{ profesor.apellido }}</li>
            {% empty %}
            <li class="list-group-item">Ninguno por el momento...</li>
            {% endfor %}
        </ul>
    </div>

    <!--
    Esta parte en teoria deberia mostrar todos los horarios de la semana disponibles para la asignatura
    -->

    <hr/>
    <div class="card text-center">
        <div class="card-header">
            <b>Posibles horarios semanales</b>
        </div>
        <div class="card-body">
            <div class="table-responsive">
              <table class="table">
                <thead>
                    <th>Bloque</th>
                    <th>Lunes</th>
                    <th>Martes</th>
                    <th>Miércoles</th>
                    <th>Jueves</th>
                    <th>Viernes</th>
                    <th>Sábado</th>
                </thead>
                <tbody>
                    {% for bloque in matriz_bloques %}
                        <tr>
                            <td><strong>{{ bloque }}</strong></td>
                            {% for disponibilidad in matriz_bloques|dict_key:bloque %}
                                <td>
                                    {% if disponibilidad in lista_disponibilidades %}
                                        SÍ
                                    {% endif %}
                                </td>
                            {% endfor %}
                        </tr>
                    {% endfor %}
                </tbody>
              </table>
            </div>
        </div>
    </div>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
</div>