gestion/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from gestion import views, forms

app_name = "gestion"

urlpatterns = [
    url(r'^$', views.Dashboard.as_view(), name='dashboard'),
    url(r'^profesores/$', views.ListarProfesores.as_view(), name='listar-profesores'),
    url(r'^profesores/agregar/$', views.AgregarProfesor.as_view(), name='agregar-profesor'),
    url(r'^profesores/editar/(?P<pk>[-\w]+)/$', views.EditarProfesor.as_view() , name='editar-profesor'),
    url(r'^profesores/eliminar/(?P<pk>[-\w]+)/$', views.EliminarProfesor.as_view() , name='eliminar-profesor'),
    url(r'^profesores/(?P<pk>[-\w]+)/$', views.VerProfesor.as_view(), name='ver-profesor'),
    url(r'^asignaturas/$', views.ListarAsignaturas.as_view(), name='listar-asignaturas'),
    url(r'^asignaturas/agregar/$', views.AgregarAsignatura.as_view(), name='agregar-asignatura'),
    url(r'^asignaturas/editar/(?P<pk>[-\w]+)/$', views.EditarAsignatura.as_view() , name='editar-asignatura'),
    url(r'^asignaturas/eliminar/(?P<pk>[-\w]+)/$', views.EliminarAsignatura.as_view() , name='eliminar-asignatura'),
    url(r'^asignaturas/(?P<pk>[-\w]+)/$', views.VerAsignatura.as_view(), name='ver-asignatura'),
    url(r'^ofertas/$', views.ListarOfertas.as_view(), name='listar-ofertas'),
    url(r'^ofertas/agregar/$', views.AgregarOferta.as_view([
        forms.AgregarOfertaTrimestralPaso1,
        forms.AgregarOfertaTrimestralPaso2
    ]), name='agregar-oferta'),
    url(r'^ofertas/agregar/(?P<pk>[-\w]+)/$', views.AgregarOferta.as_view([
        forms.AgregarOfertaTrimestralPaso1,
        forms.AgregarOfertaTrimestralPaso2
    ]), name='agregar-oferta'),
    url(r'^ofertas/eliminar/(?P<pk>[-\w]+)/$', views.EliminarOferta.as_view(), name='eliminar-oferta'),
    url(r'^ofertas/modificar/(?P<pk>[-\w]+)/$', views.ModificarOferta.as_view(), name='modificar-oferta'),
    url(r'^ofertas/buscar/$', views.buscar_oferta, name='buscar-ofertas'),
    url(r'^ofertas/buscar/(?P<periodo>[-\w]+)/$', views.buscar_oferta, name='buscar-ofertas'),
    url(r'^ofertas/buscar/(?P<periodo>[-\w]+)/(?P<ano>[-\w]+)/$', views.buscar_oferta, name='buscar-ofertas'),
    url(r'^ofertas/(?P<pk>[-\w]+)/$', views.VerOferta.as_view(), name='ver-oferta'),
    url(r'^ofertas-asignacion/$', views.ListarOfertasIncluyentes.as_view(), name='listar-ofertas-asignacion'),
    url(r'^ofertas-asignacion/actualizar/(?P<pk_oferta>[-\w]+)/$', views.actualizar_preferencias, name='actualizar-preferencias'),
    url(r'^ofertas-asignacion/(?P<pk>[-\w]+)/$', views.VerOfertaIncluyente.as_view(), name='ver-oferta-asignacion'),
    url(r'^ofertas-coordinacion/$', views.ListarOfertasCoordinacion.as_view(), name='listar-ofertas-coordinacion'),
    url(r'^ofertas-coordinacion/(?P<pk>[-\w]+)/$', views.VerOfertaCoordinacion.as_view(), name='ver-oferta-coordinacion'),
    url(r'^cambiar-contrasena/', views.cambiar_contrasena, name='cambiar-contrasena'),
]

sip/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^login/$', auth_views.login, {'template_name': 'sesiones/login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^admin/', admin.site.urls),
    url(r'^chat/', include('conversate.urls', namespace='conversate')),
    url(r'', include('gestion.urls')),
]

templates/base-error.html
{% load static %}
<!doctype html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang=""> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %}Error 404{% endblock %} - Sistema de Inscripción de Postgrado</title>
    <meta name="description" content="Sistema de Inscripción de Postgrado">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="apple-touch-icon" href="apple-icon.png">
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}">

    <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/themify-icons.css' %}">
    <link rel="stylesheet" href="{% static 'css/flag-icon.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/cs-skin-elastic.css' %}">
    
    <link href="{% static 'css/librerias/vector-map/jqvmap.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/librerias/datatable/dataTables.bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <!-- <link rel="stylesheet" href="{% static 'css/bootstrap-select.less' %}"> -->
    <link rel="stylesheet" href="{% static 'css/librerias/chosen/chosen.min.css' %}">
    <link rel="stylesheet" href="{% static 'scss/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.custom.css' %}">

    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,600,700,800' rel='stylesheet' type='text/css'>

    <!-- <script type="text/javascript" src="https://cdn.jsdelivr.net/html5shiv/3.7.3/html5shiv.min.js"></script> -->

    {% block css %}{% endblock %}
</head>
<body class="bg-dark">


    <div class="sufee-login d-flex align-content-center flex-wrap">
        <div class="container">
            <div class="login-content">
                <div class="login-logo">
                    <a href="index.html">
                        <img class="align-content" src="{% static 'images/logo.png' %}" alt="">
                    </a>
                </div>
                <div class="login-form">
                    {% block content %} {% endblock %}
                </div>
            </div>
        </div>
    </div>


    <script src="{% static 'js/vendor/jquery-2.1.4.min.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js"></script>
    <script src="{% static 'js/plugins.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>


    <script src="{% static 'js/librerias/chart-js/Chart.bundle.js' %}"></script>
    <script src="{% static 'js/dashboard.js' %}"></script>
    <script src="{% static 'js/widgets.js' %}"></script>
    <script src="{% static 'js/librerias/vector-map/jquery.vmap.js' %}"></script>
    <script src="{% static 'js/librerias/vector-map/jquery.vmap.min.js' %}"></script>
    <script src="{% static 'js/librerias/vector-map/jquery.vmap.sampledata.js' %}"></script>
    <script src="{% static 'js/librerias/vector-map/country/jquery.vmap.world.js' %}"></script>
    <script src="{% static 'js/librerias/data-table/datatables.min.js' %}"></script>
    <script src="{% static 'js/librerias/data-table/dataTables.bootstrap.min.js' %}"></script>
    <script src="{% static 'js/librerias/data-table/dataTables.buttons.min.js' %}"></script>
    <script src="{% static 'js/librerias/data-table/buttons.bootstrap.min.js' %}"></script>
    <script src="{% static 'js/librerias/data-table/datatables-init.js' %}"></script>
    <script src="{% static 'js/librerias/chosen/chosen.jquery.min.js' %}"></script>
    <script src="{% static 'js/imasks.js' %}"></script>
    {% block js %}{% endblock %}
</body>
</html>

templates/base-site.html
{% load static %}
<!doctype html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang=""> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %}Error 404{% endblock %} - Sistema de Inscripción de Postgrado</title>
    <meta name="description" content="Sistema de Inscripción de Postgrado">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="apple-touch-icon" href="apple-icon.png">
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}">

    <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/themify-icons.css' %}">
    <link rel="stylesheet" href="{% static 'css/flag-icon.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/cs-skin-elastic.css' %}">
    
    <link href="{% static 'css/librerias/vector-map/jqvmap.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/librerias/datatable/dataTables.bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <!-- <link rel="stylesheet" href="{% static 'css/bootstrap-select.less' %}"> -->
    <link rel="stylesheet" href="{% static 'css/librerias/chosen/chosen.min.css' %}">
    <link rel="stylesheet" href="{% static 'scss/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.custom.css' %}">

    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,600,700,800' rel='stylesheet' type='text/css'>
    <script src="{% static 'js/vendor/jquery-2.1.4.min.js' %}"></script>

    <!-- <script type="text/javascript" src="https://cdn.jsdelivr.net/html5shiv/3.7.3/html5shiv.min.js"></script> -->

    {% block css %}{% endblock %}
</head>
<body class="bg-dark">


    <div class="sufee-login d-flex align-content-center flex-wrap">
        <div class="container">
            <div class="login-content">
                <div class="login-logo">
                    <a href="index.html">
                        <img class="align-content" src="{% static 'images/logo.png' %}" alt="">
                    </a>
                </div>
                <div class="login-form">
                    {% block content %} {% endblock %}
                </div>
            </div>
        </div>
    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js"></script>
    <script src="{% static 'js/plugins.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>

    <script src="{% static 'js/librerias/chart-js/Chart.bundle.js' %}"></script>
    <script src="{% static 'js/dashboard.js' %}"></script>
    <script src="{% static 'js/widgets.js' %}"></script>
    <script src="{% static 'js/librerias/vector-map/jquery.vmap.js' %}"></script>
    <script src="{% static 'js/librerias/vector-map/jquery.vmap.min.js' %}"></script>
    <script src="{% static 'js/librerias/vector-map/jquery.vmap.sampledata.js' %}"></script>
    <script src="{% static 'js/librerias/vector-map/country/jquery.vmap.world.js' %}"></script>
    <script src="{% static 'js/librerias/data-table/datatables.min.js' %}"></script>
    <script src="{% static 'js/librerias/data-table/dataTables.bootstrap.min.js' %}"></script>
    <script src="{% static 'js/librerias/data-table/dataTables.buttons.min.js' %}"></script>
    <script src="{% static 'js/librerias/data-table/buttons.bootstrap.min.js' %}"></script>
    <script src="{% static 'js/librerias/data-table/datatables-init.js' %}"></script>
    <script src="{% static 'js/librerias/chosen/chosen.jquery.min.js' %}"></script>
    <script src="{% static 'js/imasks.js' %}"></script>
    {% block js %}{% endblock %}
</body>
</html>

templates/base.html
{% load static %}
<!doctype html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang=""> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %}Inicio{% endblock %} - Sistema de Inscripción de Postgrado</title>
    <meta name="description" content="Sistema de Inscripción de Postgrado">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="apple-touch-icon" href="apple-icon.png">
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}">

    <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/themify-icons.css' %}">
    <link rel="stylesheet" href="{% static 'css/flag-icon.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/cs-skin-elastic.css' %}">

    <link href="{% static 'css/librerias/vector-map/jqvmap.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/librerias/datatable/dataTables.bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <!-- <link rel="stylesheet" href="{% static 'css/bootstrap-select.less' %}"> -->
    <link rel="stylesheet" href="{% static 'css/librerias/chosen/chosen.min.css' %}">
    <link rel="stylesheet" href="{% static 'scss/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.custom.css' %}">

    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,600,700,800' rel='stylesheet' type='text/css'>

    <!-- <script type="text/javascript" src="https://cdn.jsdelivr.net/html5shiv/3.7.3/html5shiv.min.js"></script> -->

    {% block css %}{% endblock %}
    <style>
        .no-padding-right {
            padding-right: 0 !important;
        }
    </style>
</head>
<body class="no-padding-right">


        <!-- Left Panel -->

    <aside id="left-panel" class="left-panel">
        <nav class="navbar navbar-expand-sm navbar-default">

            <div class="navbar-header">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#main-menu" aria-controls="main-menu" aria-expanded="false" aria-label="Toggle navigation">
                    <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand" href="{% url 'gestion:dashboard' %}"><img src="{% static 'images/logo.png' %}" alt="Logo"></a>
                <a class="navbar-brand hidden" href="{% url 'gestion:dashboard' %}"><img src="{% static 'images/logo2.png' %}" alt="Logo"></a>
            </div>

            {% include 'sidebar.html' %}
        </nav>
    </aside><!-- /#left-panel -->

    <!-- Left Panel -->

    <!-- Right Panel -->

    <div id="right-panel" class="right-panel">

        <!-- Header-->
        <header id="header" class="header">

            <div class="header-menu">

                <div class="col-sm-7">
                    <a id="menuToggle" class="menutoggle pull-left"><i class="fa fa fa-tasks"></i></a>
                    <div class="header-left">

                    </div>
                </div>

                <div class="col-sm-5">
                    <div class="user-area dropdown float-right">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <img class="user-avatar rounded-circle" src="{% static 'images/admin.jpg' %}" alt="User Avatar">
                        </a>

                        <div class="user-menu dropdown-menu">
                                <a class="nav-link" href="{% url 'gestion:cambiar-contrasena' %}">
                                    <i class="fa fa-power -off"></i>Cambiar contraseña
                                </a>
                                <a class="nav-link" href="{% url 'logout' %}"><i class="fa fa-power -off"></i>Cerrar sesión</a>
                        </div>
                    </div>

                </div>
            </div>

        </header><!-- /header -->
        <!-- Header-->

        <div class="content mt-3">

            {% block content %}
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <h4>Hola</h4>
                    </div>
                    <div class="card-body">
                        Hola, aquí hay contenido.
                    </div>
                </div>
            </div>
            {% endblock %}

        </div> <!-- .content -->

        <div class="breadcrumbs footer navbar-fixed-bottom fixed-bottom">
            <div class="col-sm-4">
                <div class="page-header float-left">
                    <div class="page-title">
                        <h1>Sistema de Inscripción de Postgrado (SIP)</h1>
                    </div>
                </div>
            </div>
            <div class="col-sm-8">
                <div class="page-header float-right">
                    <div class="page-title">
                        <ol class="breadcrumb text-right">
                            <li class="active">&copy; 2018 Universidad Simón Bolívar</li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>

    </div><!-- /#right-panel -->

    <!-- Right Panel -->

    <script src="{% static 'js/vendor/jquery-2.1.4.min.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js"></script>
    <script src="{% static 'js/plugins.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>


    <script src="{% static 'js/dashboard.js' %}"></script>
    <script src="{% static 'js/widgets.js' %}"></script>
    <script src="{% static 'js/librerias/vector-map/jquery.vmap.js' %}"></script>
    <script src="{% static 'js/librerias/vector-map/jquery.vmap.min.js' %}"></script>
    <script src="{% static 'js/librerias/vector-map/jquery.vmap.sampledata.js' %}"></script>
    <script src="{% static 'js/librerias/vector-map/country/jquery.vmap.world.js' %}"></script>
    <script src="{% static 'js/librerias/data-table/datatables.min.js' %}"></script>
    <script src="{% static 'js/librerias/data-table/dataTables.bootstrap.min.js' %}"></script>
    <script src="{% static 'js/librerias/data-table/dataTables.buttons.min.js' %}"></script>
    <script src="{% static 'js/librerias/data-table/buttons.bootstrap.min.js' %}"></script>
    <script src="{% static 'js/librerias/data-table/datatables-init.js' %}"></script>
    <script src="{% static 'js/librerias/chosen/chosen.jquery.min.js' %}"></script>
    <script src="{% static 'js/imasks.js' %}"></script>

    <script>
        jQuery(document).ready(function() {
            jQuery(".standardSelect").chosen({
                disable_search_threshold: 10,
                no_results_text: "¡No se encontró ningún resultado!",
                width: "100%"
            });
        });
    </script>

    {% block js %}{% endblock %}
</body>
</html>

templates/dashboard.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Inicio{% endblock %}

{% block content %}
<div class="row">
    <!-- Tarjeta de bienvenida -->
    <div class="col-lg-6">
        <div class="card">
            <div class="card-header">
                <h4>Inicio</h4>
            </div>
            <div class="card-body">
                ¡Bienvenido al Sistema de Inscripción de Postgrado Online!
            </div>
        </div>
    </div>


    <!-- Widget de perfil de usuario -->
    <div class="col-lg-6">
        <aside class="profile-nav alt">
            <section class="card">
                <div class="card-header user-header alt bg-dark">
                    <div class="media">
                        <a href="#">
                            <img class="align-self-center rounded-circle mr-3" style="width:50px; height:50px;" alt="" src="{% static 'images/admin.jpg' %}">
                        </a>
                        <div class="media-body">
                            <h2 class="text-light display-6">
                                {% if request.user.first_name and request.user.last_name %}
                                    {{ request.user.first_name }} {{ request.user.last_name }}
                                {% elif request.user.username %}
                                    {{ request.user.username }}
                                {% else %}
                                    Usuario
                                {% endif %}
                            </h2>
                            <h4 style="color: white;">
                                {% if request.user.profesor.es_jefe %}
                                    Jefe de Departamento
                                    {% else %}
                                    Profesor
                                {% endif %}
                            </h4>
                            <p>
                                {{ request.user.profesor.departamento }}
                            </p>
                            {% if request.user.profesor.es_coordinador %}
                            <h4 style="color: white;">Coordinador</h4>
                            <p>
                                {{ request.user.profesor.coordinacion }}
                            </p>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </section>
        </aside>
    </div>
</div>

<div class="row">
    <!-- Widget de Departamentos -->
    <div class="col-lg-6">
        <div class="card">
            <div class="card-body">
                <div class="stat-widget-one">
                    <div class="stat-icon dib"><i class="ti-folder text-success border-success"></i></div>
                    <div class="stat-content dib">
                        <div class="stat-text">Departamentos agregados</div>
                        <div class="stat-digit">{{ departamentos }}</div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Widget de Coordinaciones -->
    <div class="col-lg-6">
        <div class="card">
            <div class="card-body">
                <div class="stat-widget-one">
                    <div class="stat-icon dib"><i class="ti-file text-danger border-danger"></i></div>
                    <div class="stat-content dib">
                        <div class="stat-text">Coordinaciones agregadas</div>
                        <div class="stat-digit">{{ coordinaciones }}</div>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <!-- Widget de Profesores -->
    <div class="col-lg-6">
        <div class="card">
            <div class="card-body">
                <div class="stat-widget-one">
                    <div class="stat-icon dib"><i class="ti-user text-primary border-primary"></i></div>
                    <div class="stat-content dib">
                        <div class="stat-text">Profesores agregados</div>
                        <div class="stat-digit">{{ profesores }}</div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Widget de Asignaturas -->
    <div class="col-lg-6">
        <div class="card">
            <div class="card-body">
                <div class="stat-widget-one">
                    <div class="stat-icon dib"><i class="ti-layout-grid2 text-warning border-warning"></i></div>
                    <div class="stat-content dib">
                        <div class="stat-text">Asignaturas agregadas</div>
                        <div class="stat-digit">{{ asignaturas }}</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/sidebar.html
<div id="main-menu" class="main-menu collapse navbar-collapse">
    <ul class="nav navbar-nav">
        <li class="active">
            <a href="{% url 'gestion:dashboard' %}"> <i class="menu-icon fa fa-dashboard"></i>Inicio </a>
        </li>
        {% if request.user.profesor.es_jefe %}
        <h3 class="menu-title">Profesores</h3><!-- /.menu-title -->
        <li>
            <a href="{% url 'gestion:listar-profesores' %}"> <i class="menu-icon fa fa-group"></i>Gestionar profesores</a>
        </li>

        <h3 class="menu-title">Asignaturas</h3><!-- /.menu-title -->
        <li>
            <a href="{% url 'gestion:listar-asignaturas' %}"> <i class="menu-icon fa fa-bookmark"></i>Gestionar asignaturas</a>
        </li>
        {% endif %}


        <h3 class="menu-title">Ofertas</h3><!-- /.menu-title -->
        <li>
            {% if request.user.profesor.es_jefe %}
                <a href="{% url 'gestion:listar-ofertas' %}"> <i class="menu-icon fa fa-bookmark"></i>Gestionar ofertas</a>
            {% endif %}
            <a href="{% url 'gestion:buscar-ofertas' %}"> <i class="menu-icon fa fa-search"></i>Buscar ofertas</a>
        </li>

        {% if request.user.profesor.es_coordinador %}
        <h3 class="menu-title">Coordinación</h3><!-- /.menu-title -->
        <li>
            <a href="{% url 'gestion:listar-ofertas-coordinacion' %}"> <i class="menu-icon fa fa-bookmark"></i>Ofertas disponibles</a>
        </li>
        {% endif %}

        <h3 class="menu-title">Preferencias del trimestre</h3><!-- /.menu-title -->
        <li>
            <a href="{% url 'gestion:listar-ofertas-asignacion' %}"> <i class="menu-icon fa fa-gear"></i>Gestionar preferencias</a>
        </li>

    </ul>
</div><!-- /.navbar-collapse -->

templates/template-modal.html
<div class="modal-header">
    <h5 class="modal-title" id="largeModalLabel">Título del modal</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<div class="modal-body">
    <p>
        Contenido del modal
    </p>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
    <button type="button" class="btn btn-primary">Confirmar</button>
</div>

templates/template.html
{% extends 'base.html' %}

{% block title %}Título de la página{% endblock %}

{% block content %}
<div class="col-md-12">
    <div class="card">
        <div class="card-header">
            <h4>Hola</h4>
        </div>
        <div class="card-body">
            Hola, aquí hay contenido.
        </div>
    </div>
</div>
{% endblock %}

{% block js %}
<script type="text/javascript">
	// Aquí va etiquetas javascript personalizadas si tienen
</script>
{% endblock %}

{% block css %}
<style type="text/css">
/* Aquí va codigo css personalziado dentro de etiquetas style */
</style>
{% endblock %}